[package]
description = "Substrate transaction protocol (patched: Clone on controller)"
name = "sc-network-transactions"
version = "0.50.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2024"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/polkadot-sdk"
documentation = "https://docs.rs/sc-network-transactions"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { version = "6.2.3", default-features = true }
codec = { package = "parity-scale-codec", version = "3.7.5", default-features = true, features = ["derive"] }
futures = { version = "0.3.31" }
log = { version = "0.4.22", default-features = true }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/opentensor/polkadot-sdk.git", rev = "7cc54bf2d50ae3921d718736dfeb0de9468539c7", default-features = true }
sc-network = { path = "../sc-network", default-features = true }
sc-network-common = { git = "https://github.com/opentensor/polkadot-sdk.git", rev = "7cc54bf2d50ae3921d718736dfeb0de9468539c7", default-features = true }
sc-network-sync = { git = "https://github.com/opentensor/polkadot-sdk.git", rev = "7cc54bf2d50ae3921d718736dfeb0de9468539c7", default-features = true }
sc-network-types = { git = "https://github.com/opentensor/polkadot-sdk.git", rev = "7cc54bf2d50ae3921d718736dfeb0de9468539c7", default-features = true }
sc-utils = { git = "https://github.com/opentensor/polkadot-sdk.git", rev = "7cc54bf2d50ae3921d718736dfeb0de9468539c7", default-features = true }
sp-consensus = { git = "https://github.com/opentensor/polkadot-sdk.git", rev = "7cc54bf2d50ae3921d718736dfeb0de9468539c7", default-features = true }
sp-runtime = { git = "https://github.com/opentensor/polkadot-sdk.git", rev = "7cc54bf2d50ae3921d718736dfeb0de9468539c7", default-features = true }
